### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by J-Jaeh** [swjunglePintos1Team5/Pintos#2]
- [x]  tests/threads/alarm-single
- [x]  tests/threads/alarm-multiple
- [x]  tests/threads/alarm-simultaneous
- [x]  tests/threads/alarm-priority
- [x]  tests/threads/alarm-zero
- [x]  tests/threads/alarm-negative
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x]  tests/threads/mlfqs/mlfqs-fair-2
- [x]  tests/threads/mlfqs/mlfqs-fair-20
- [ ] #15
- [ ] #16
- [ ] #17
- [ ] #18
- [ ] #19
- [ ] #20
- [ ] #21
